const ROLES = Object.freeze({
  COMMUNITY: "COMMUNITY",
  COLLECTOR: "COLLECTOR",
  STAKEHOLDER: "STAKEHOLDER",
});

const SUBMISSION_STATUS = Object.freeze({
  SUBMITTED: "SUBMITTED",
  ACCEPTED_BY_COLLECTOR: "ACCEPTED_BY_COLLECTOR",
  REJECTED_BY_COLLECTOR: "REJECTED_BY_COLLECTOR",
  IN_BATCH: "IN_BATCH",
  COMPLETED: "COMPLETED",
});

const BATCH_STATUS = Object.freeze({
  SUBMITTED_TO_STAKEHOLDER: "SUBMITTED_TO_STAKEHOLDER",
  LAB_REVIEW: "LAB_REVIEW",
  ACCEPTED_BY_STAKEHOLDER: "ACCEPTED_BY_STAKEHOLDER",
  REJECTED_BY_STAKEHOLDER: "REJECTED_BY_STAKEHOLDER",
});

const LAB_GRADES = Object.freeze({
  A: "A",
  B: "B",
  C: "C",
  REJECT: "REJECT",
});

const AUDIT_ACTIONS = Object.freeze({
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  ACCEPT: "ACCEPT",
  REJECT: "REJECT",
  FINAL_VALIDATE: "FINAL_VALIDATE",
  CORRECTION: "CORRECTION",
});

const AUDIT_ENTITY_TYPES = Object.freeze({
  STAKEHOLDER_SETTING: "STAKEHOLDER_SETTING",
  COMMUNITY_SUBMISSION: "COMMUNITY_SUBMISSION",
  COLLECTOR_BATCH: "COLLECTOR_BATCH",
  LAB_RESULT: "LAB_RESULT",
});

module.exports = {
  BATCH_STATUS,
  LAB_GRADES,
  ROLES,
  SUBMISSION_STATUS,
  AUDIT_ACTIONS,
  AUDIT_ENTITY_TYPES
};
