const ROLES = Object.freeze({
  COMMUNITY: 'COMMUNITY',
  COLLECTOR: 'COLLECTOR',
  STAKEHOLDER: 'STAKEHOLDER',
});

const SUBMISSION_STATUS = Object.freeze({
  SUBMITTED: 'SUBMITTED',
  ACCEPTED_BY_COLLECTOR: 'ACCEPTED_BY_COLLECTOR',
  REJECTED_BY_COLLECTOR: 'REJECTED_BY_COLLECTOR',
  IN_BATCH: 'IN_BATCH',
  COMPLETED: 'COMPLETED',
});

module.exports = { ROLES, SUBMISSION_STATUS };
