const ROLES = Object.freeze({
  COMMUNITY: 'COMMUNITY',
  COLLECTOR: 'COLLECTOR',
  STAKEHOLDER: 'STAKEHOLDER',
});

const SUBMISSION_STATUS = Object.freeze({
  SUBMITTED: 'SUBMITTED',
  ACCEPTED_BY_COLLECTOR: 'ACCEPTED_BY_COLLECTOR',
  REJECTED_BY_COLLECTOR: 'REJECTED_BY_COLLECTOR',
  IN_BATCH: 'IN_BATCH',
  COMPLETED: 'COMPLETED',
});

const BATCH_STATUS = Object.freeze({
  SUBMITTED_TO_STAKEHOLDER: 'SUBMITTED_TO_STAKEHOLDER',
  LAB_REVIEW: 'LAB_REVIEW',
  ACCEPTED_BY_STAKEHOLDER: 'ACCEPTED_BY_STAKEHOLDER',
  REJECTED_BY_STAKEHOLDER: 'REJECTED_BY_STAKEHOLDER',
});

module.exports = { BATCH_STATUS, ROLES, SUBMISSION_STATUS };
